FROM node:18-alpine3.17

WORKDIR /app

COPY package.json .
COPY package-lock.json .

ARG REACT_APP_BACKEND_URL
ARG REACT_APP_WS_URL
ARG REACT_APP_BUILD_HASH

ENV REACT_APP_BACKEND_URL ${REACT_APP_BACKEND_URL}
ENV REACT_APP_WS_URL ${REACT_APP_WS_URL}
ENV REACT_APP_BUILD_HASH ${REACT_APP_BUILD_HASH}

ENV WATCHPACK_POLLING=true
ENV REACT_APP_PROXY_TARGET=${REACT_APP_BACKEND_URL}

RUN npm ci

COPY . .

CMD ["npm", "start"]