version: '3.9'

services:

  frontend.web.interview:
    container_name: "frontend.web.interview"

    build:
      context: ../
      dockerfile: docker/proxy/Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:9000
        - REACT_APP_VERSION=1.0.0-Docker
        - NGINX_DOMAIN=localhost
        - NGINX_SECURITY_BACKEND_URL=http://localhost:9000
    ports:
      - "9020:80"
